/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface_Airline;
import Business.Abstract.User;
import UserInterface.LoginScreen;
import java.awt.CardLayout;
import javax.swing.JPanel;
import Business.Users.Admin;
import Business.Users.Airliner;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import Business.Users.Airliner;
import Business.Flight;
import Business.FlightDirectory;
/**
 *
 * @author Abhi
 */
public class AirlinerScreen extends javax.swing.JPanel {

    /**
     * Creates new form AirlinerScreen
     */
    JPanel panelRight;
    User user;
    List<User> list;
    Admin adminUser;
    Airliner airliner;
    Flight flight;
    FlightDirectory flightDir;
    public AirlinerScreen(JPanel panelRight ,User user,List<User> list,FlightDirectory flightDir) {
        
        this.panelRight=panelRight;
        this.user=user;
        this.list=list;
        this.flightDir=flightDir;
        initComponents();
        //populate();
    }

    
    public void populate(){
        
        
        DefaultTableModel dtm = (DefaultTableModel)tableSup.getModel();
        dtm.setRowCount(0);
       
        
        for(Flight u : airliner.getDirectory().getFlightList()){
            
            Object[] row = new Object[dtm.getColumnCount()];
            row[0]=u;
            row[1]=u.getFlight_name();
            row[2]=u.getDes_to();
            row[3]=u.getNum_of_seats();
            row[4]=u.getLoc_from();
            row[5]=u.getPrice();
            dtm.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tableSup = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        logoutjButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        tableSup.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flight Name", "Price", "Number of seats", "From", "To", "Time"
            }
        ));
        jScrollPane2.setViewportView(tableSup);

        jButton1.setText("Create New Flight ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Update Flight");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        logoutjButton.setText("Logout");
        logoutjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutjButtonActionPerformed(evt);
            }
        });

        jButton3.setText("Delete a Flight");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(102, 102, 102)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(logoutjButton)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoutjButton)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(165, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        NewFlight panel=new NewFlight(panelRight,user,list,flightDir);
        panelRight.add(panel);
            CardLayout layout =(CardLayout)panelRight.getLayout();
            
            layout.next(panelRight);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        UpdateFlight panel=new UpdateFlight(panelRight,user,list);
        panelRight.add(panel);
            CardLayout layout =(CardLayout)panelRight.getLayout();
            
            layout.next(panelRight);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void logoutjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutjButtonActionPerformed
        // TODO add your handling code here:
        CardLayout layout=(CardLayout)panelRight.getLayout();
        panelRight.add(new LoginScreen(panelRight,list));
        layout.next(panelRight);
        
    }//GEN-LAST:event_logoutjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton logoutjButton;
    private javax.swing.JTable tableSup;
    // End of variables declaration//GEN-END:variables
}
