/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface_Customer;

import Business.Users.Admin;
import javax.swing.JPanel;
/**
 *
 * @author chief_kmv
 */
    
   
public class CustomerScreen extends javax.swing.JPanel {
    

    /**
     * Creates new form CustomerScreen
     */
    public CustomerScreen(JPanel rightPanel,Admin travelAgency) {
        initComponents();
         this.rightPanel=rightPanel;
        this.user=user;
        this.list=list;
       
       
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bookbtn = new javax.swing.JButton();
        ViewHistorybtn = new javax.swing.JButton();
        lblPastBookings = new javax.swing.JLabel();

        bookbtn.setBackground(new java.awt.Color(245, 245, 246));
        bookbtn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        bookbtn.setForeground(new java.awt.Color(78, 114, 175));
        bookbtn.setText("Book Flights");
        bookbtn.setMaximumSize(new java.awt.Dimension(155, 31));
        bookbtn.setMinimumSize(new java.awt.Dimension(155, 31));
        bookbtn.setPreferredSize(new java.awt.Dimension(155, 31));
        bookbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookbtnActionPerformed(evt);
            }
        });

        ViewHistorybtn.setBackground(new java.awt.Color(245, 245, 246));
        ViewHistorybtn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        ViewHistorybtn.setForeground(new java.awt.Color(78, 114, 175));
        ViewHistorybtn.setText("View Past Bookings");
        ViewHistorybtn.setMaximumSize(new java.awt.Dimension(155, 31));
        ViewHistorybtn.setMinimumSize(new java.awt.Dimension(155, 31));
        ViewHistorybtn.setPreferredSize(new java.awt.Dimension(155, 31));
        ViewHistorybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewHistorybtnActionPerformed(evt);
            }
        });

        lblPastBookings.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lblPastBookings.setForeground(new java.awt.Color(78, 114, 175));
        lblPastBookings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPastBookings.setText("MANAGE CUSTOMERS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(397, Short.MAX_VALUE)
                .addComponent(bookbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(308, 308, 308))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPastBookings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(106, 106, 106))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(362, Short.MAX_VALUE)
                    .addComponent(ViewHistorybtn, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(282, 282, 282)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(lblPastBookings)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 336, Short.MAX_VALUE)
                .addComponent(bookbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(240, 240, 240))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(355, Short.MAX_VALUE)
                    .addComponent(ViewHistorybtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(336, 336, 336)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bookbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookbtnActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_bookbtnActionPerformed

    private void ViewHistorybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewHistorybtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewHistorybtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ViewHistorybtn;
    private javax.swing.JButton bookbtn;
    private javax.swing.JLabel lblPastBookings;
    // End of variables declaration//GEN-END:variables
}
