/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface_Customer;
import Business.Users.Airliner;
import Business.Users.Customer;
import Business.Flight;
import Business.Seats;
import Business.Users.Admin;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Abhi
 */
public class PastBooking extends javax.swing.JPanel {

    /**
     * Creates new form PastBooking
     */
    private JPanel cardSequenceJPanel;
    private Admin travelAgency;
    private Flight flight;
    private Seats seat;
    public PastBooking (JPanel cardSequenceJPanel,Admin travelAgency) {
        initComponents();
        this.cardSequenceJPanel = cardSequenceJPanel;
        this.travelAgency = travelAgency;
        populatePastBookingsJTable();
    
    }
    private void populatePastBookingsJTable(){
        DefaultTableModel table = (DefaultTableModel) tblPastBookings.getModel();
        table.setRowCount(0);
        for(Customer customer : travelAgency.getCustDir().getCustomerList()){
            Object row[] = new Object[5];
            row[0]=customer;
            row[1]=customer.getCustomerContact();
            row[2]=customer.getCustomerEmail();
            row[3]=customer.getFlightNumber();
            row[4]=customer.getSeatNumber();
            table.addRow(row);
        }
    }
     
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPastBookings = new javax.swing.JTable();
        lblPastBookings = new javax.swing.JLabel();
        btnDeleteBooking = new javax.swing.JButton();

        btnBack.setBackground(new java.awt.Color(245, 245, 246));
        btnBack.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(78, 114, 175));
        btnBack.setText("< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        tblPastBookings.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Contact", "Email", "Flight Number", "Seat Number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPastBookings);

        lblPastBookings.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lblPastBookings.setForeground(new java.awt.Color(78, 114, 175));
        lblPastBookings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPastBookings.setText("Past Bookings");

        btnDeleteBooking.setBackground(new java.awt.Color(245, 245, 246));
        btnDeleteBooking.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnDeleteBooking.setForeground(new java.awt.Color(78, 114, 175));
        btnDeleteBooking.setText("Cancel Booking");
        btnDeleteBooking.setMaximumSize(new java.awt.Dimension(155, 31));
        btnDeleteBooking.setMinimumSize(new java.awt.Dimension(155, 31));
        btnDeleteBooking.setPreferredSize(new java.awt.Dimension(155, 31));
        btnDeleteBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteBookingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPastBookings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(137, 137, 137))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 169, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(159, 159, 159))))
            .addGroup(layout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(btnDeleteBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBack)
                    .addComponent(lblPastBookings))
                .addGap(63, 63, 63)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDeleteBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(197, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        cardSequenceJPanel.remove(this);
        CardLayout layout = (CardLayout) cardSequenceJPanel.getLayout();
        layout.previous(cardSequenceJPanel);
       
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDeleteBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteBookingActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblPastBookings.getSelectedRow();
        if(selectedRow  >= 0) {
           int dialogButton = JOptionPane.YES_NO_OPTION;
           int dialogResult = JOptionPane.showConfirmDialog(null,"Would you like to cancel the booking ?","Warning",dialogButton);
           if(dialogResult == JOptionPane.YES_OPTION) {
               Customer customer = (Customer)tblPastBookings.getValueAt(selectedRow,0);
               for(Airliner airliner:travelAgency.getAirDir().getAirlinerList()) {
                for(Flight flight:airliner.getFlightList()) {
                    if(flight.getFlightNumber().equals(customer.getFlightNumber())){
                          for(Seats seat:flight.getSeatList()){
                            if(seat.getSeatNumber().equals(customer.getSeatNumber()))
                                seat.setSeatAvailability(true);
                            }
                          flight.setAvailableSeats(flight.getAvailableSeats()+1);
                    }
            
               
            }
        }
               
               
               travelAgency.getCustDir().deleteCustomer(customer);
               populatePastBookingsJTable();
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Please select a row from table first","Warning",JOptionPane.WARNING_MESSAGE);
        }
                                                

       
    }//GEN-LAST:event_btnDeleteBookingActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeleteBooking;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPastBookings;
    private javax.swing.JTable tblPastBookings;
    // End of variables declaration//GEN-END:variables
}