/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DoctorWorkArea;

import Business.Enterprise.Enterprise;
import Business.LabTest.LabTest;
import Business.Main.EcoSystem;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.WorkQueue.DoctorRequest;
import Business.WorkQueue.UNOS_Request;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author chief_kmv
 */
public class TestResults extends javax.swing.JPanel {

    /**
     * Creates new form TestResults
     */
     private JPanel userProcessContainer;
    private DoctorRequest request;
    private EcoSystem business;
    public TestResults(JPanel userProcessContainer, WorkRequest request, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = (DoctorRequest) request;
        this.business = business;
        populateFields();
    }
     public void populateFields() {
        LabTest test = request.getLabtest();
        bloodtypeTxt.setText(test.getBloodType());
        sugarTxt.setText(test.getBloodSugar());
        infectiousTxt.setText(test.getInfectiousDiseases());
        tissueTxt.setText(test.getTissueType());
        resultJTextField1.setText(test.getTestResult());
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bloodtypeTxt = new javax.swing.JTextField();
        resultJTextField1 = new javax.swing.JTextField();
        infectiousTxt = new javax.swing.JTextField();
        sugarTxt = new javax.swing.JTextField();
        tissueTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        SendBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        msgTxt = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setText("Result");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, -1, 30));
        add(bloodtypeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 88, -1));
        add(resultJTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, 88, -1));
        add(infectiousTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 88, -1));
        add(sugarTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 88, -1));
        add(tissueTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 88, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setText("Infectious Diseases");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, -1, 20));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setText("Blood Type");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel4.setText("Tissue Type");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, -1, 20));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel5.setText("Blood Sugar");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, -1, -1));

        backJButton.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        SendBtn.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        SendBtn.setText("Send To Registry");
        SendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendBtnActionPerformed(evt);
            }
        });
        add(SendBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 530, -1, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel7.setText("Message");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, -1, -1));

        msgTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msgTxtActionPerformed(evt);
            }
        });
        add(msgTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, 110, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void SendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendBtnActionPerformed
        // TODO add your handling code here:
        UNOS_Request optc_req=new UNOS_Request();
        optc_req.setPatient(request.getPatient());
        optc_req.setLabtest(request.getLabtest());
        optc_req.setSender(request.getSender());
        optc_req.setStatus("Sent to Registry");
        optc_req.setMessage(msgTxt.getText());
        if (request.getPatient().getType().equals("Donor")) {
            for (Network network : business.getNetworkList()) {
               // System.out.println(network);
                for (Enterprise ent : network.getEnterpriseDirectory().getEnterpriseList()) {
                    //System.out.println(ent);
                    if(ent.getEnterpriseType().toString().equals("United Network of Organ Sharing")){
                        
                        for(Organization org:ent.getOrganizationDirectory().getOrganizationList()){
                            org.getWorkQueue().addRequest(optc_req);
                           
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_SendBtnActionPerformed

    private void msgTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msgTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_msgTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SendBtn;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField bloodtypeTxt;
    private javax.swing.JTextField infectiousTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField msgTxt;
    private javax.swing.JTextField resultJTextField1;
    private javax.swing.JTextField sugarTxt;
    private javax.swing.JTextField tissueTxt;
    // End of variables declaration//GEN-END:variables
}
