/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.OPTC_Registry;

import Business.Enterprise.Enterprise;
import Business.Enterprise.OPTC_Enterprise;
import Business.Main.EcoSystem;
import Business.Organization.Organization;
import Business.UserAccount.Reciever;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.OPTC_Request;
import Business.WorkQueue.RecieverWorkReq;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chief_kmv
 */
public class ManageEmergencyReq extends javax.swing.JPanel {

    /**
     * Creates new form ManageEmergencyReq
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private OPTC_Enterprise enterprise;
    private EcoSystem business;

    public ManageEmergencyReq(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.account = account;
        this.enterprise = (OPTC_Enterprise) enterprise;
        this.business = business;
        this.userProcessContainer = userProcessContainer;
        populateRequestTable();
        populateCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        backJButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        recieverCombo = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Request ID", "Donor Name", "Organ Reciever Name", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(workRequestJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 550, 90));

        backJButton.setBackground(new java.awt.Color(247, 23, 53));
        backJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/Go-back-icon.png"))); // NOI18N
        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 159, 28));
        jButton1.setText("Send Organ Reciever");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 480, -1, -1));

        jLabel1.setText("Set Reciever");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, -1, 20));

        recieverCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(recieverCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 390, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    public void populateCombo() {
        recieverCombo.removeAllItems();

        for (UserAccount user : enterprise.getUserAccountDirectory().getUserAccountList()) {
            if (user.getRole().toString().equals("Business.Role.RecieverRole")) {
                recieverCombo.addItem(user);
            }
        }
    }

    public void populateRequestTable() {
        DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();

        model.setRowCount(0);
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            for (WorkRequest request : organization.getWorkQueue().getWorkRequestList()) {

                if (request.getStatus().equals("Sent to OPTC") || request.getStatus().equals("Sent Reciever") ) {
                    Object[] row = new Object[4];
                    row[0] = request;
                    row[1] = ((RecieverWorkReq) request).getDonor();

                    row[2] = ((RecieverWorkReq) request).getOrganReciever();
                    row[3] = request.getStatus();
                    model.addRow(row);
                }
            }
        }
    }
    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        int selectedRow = workRequestJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table to view details", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {

            RecieverWorkReq request = (RecieverWorkReq) workRequestJTable.getValueAt(selectedRow, 0);
            Reciever reciever = (Reciever) recieverCombo.getSelectedItem();
            if (request.getStatus().equals("Sent Reciever")) {
                JOptionPane.showMessageDialog(null,"Organ Reciever Info already Sent to emergency Services" );
            } else {
                ((RecieverWorkReq) request).setOrganReciever(reciever);
                request.setReceiver(account);
                request.setStatus("Sent Reciever");
                populateRequestTable();
                enterprise.getUserAccountDirectory().getUserAccountList().remove(reciever);
                populateCombo();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox recieverCombo;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
