/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.RecieverArea;

import Business.Enterprise.Enterprise;
import Business.UserAccount.Reciever;
import Business.UserAccount.UserAccount;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author chief_kmv
 */
public class RecieverMainPanel extends javax.swing.JPanel {

    /**
     * Creates new form RecieverMainPanel
     */
    Reciever account;
    JPanel userProcessContainer;
    Enterprise enterprise;
    int k;
    public RecieverMainPanel(JPanel userProcessContainer, UserAccount account,Enterprise enterprise) {
        initComponents();
        this.account=(Reciever) account;
        this.userProcessContainer=userProcessContainer;
        this.enterprise=enterprise;
        populateFields();
    }
    
      public void populateFields() {
        nameTxt.setText(account.getInfo().getName());
//        DobTxt.setText(request.getPatient().getDob());
        jXDatePicker1.setDate(account.getInfo().getDob());
        organTxt.setText(account.getOrganReq());
        resultTxt.setText(account.getLabTest().getTestResult());
        ssnTxt.setText(account.getInfo().getSsn());
        k=0;
        for(UserAccount user : enterprise.getUserAccountDirectory().getUserAccountList()){
            if(user.getRole().toString().equals("Business.Role.RecieverRole")){
                if(user.getUsername().equals(account.getUsername())){
                    waitTxt.setText(Integer.toString(k));
                }
                k++;
            }
        }
        
         nameTxt.setEnabled(false);
        jXDatePicker1.setEnabled(false);
        organTxt.setEnabled(false);
        resultTxt.setEnabled(false);
        ssnTxt.setEnabled(false);
        waitTxt.setEnabled(false);

        try {
            String path = account.getInfo().getImage();

            if (path.isEmpty() || path == null || path.equals("")) {
                imageLabel.setText("Image Not Uploaded");
            } else {
                ImageIcon image = new ImageIcon(path);
                image.setImage(image.getImage().getScaledInstance(100, 150, Image.SCALE_DEFAULT));
                imageLabel.setIcon(image);
            }
            imageLabel.setText("");
        } catch (Exception e) {
            System.out.println("error");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        resultTxt = new javax.swing.JTextField();
        nameTxt = new javax.swing.JTextField();
        organTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        jLabel7 = new javax.swing.JLabel();
        ssnTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        waitTxt = new javax.swing.JTextField();
        imageLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 204, 204));
        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setText("Lab Test Result");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, -1, -1));
        add(resultTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, 100, -1));

        nameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTxtActionPerformed(evt);
            }
        });
        add(nameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 100, -1));
        add(organTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 100, -1));

        jLabel2.setBackground(new java.awt.Color(0, 204, 204));
        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setText("Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 204, 204));
        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setText("Date of Birth:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, -1, -1));

        jLabel4.setBackground(new java.awt.Color(0, 204, 204));
        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel4.setText("Organ Needed:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, -1, -1));
        add(jXDatePicker1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, -1, -1));

        jLabel7.setBackground(new java.awt.Color(0, 204, 204));
        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel7.setText("SSN:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, -1, -1));
        add(ssnTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 110, -1));

        jLabel5.setBackground(new java.awt.Color(0, 204, 204));
        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel5.setText("Waiting Number:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, -1, -1));
        add(waitTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 470, 210, -1));

        imageLabel.setText("No Image Found");
        add(imageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 90, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/Patients-icon.png"))); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void nameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JTextField organTxt;
    private javax.swing.JTextField resultTxt;
    private javax.swing.JTextField ssnTxt;
    private javax.swing.JTextField waitTxt;
    // End of variables declaration//GEN-END:variables
}
