/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.EmergencyServices;

import Business.Enterprise.Enterprise;
import Business.Main.EcoSystem;
import Business.Network.Network;
import Business.Organization.EmergencyServicesOrganization;
import Business.Organization.Organization;
import Business.UserAccount.Donor;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.RecieverWorkReq;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author chief_kmv
 */
public class CheckDonor extends javax.swing.JPanel {

    /**
     * Creates new form CheckDonor
     */
    JPanel userProcessContainer;
    private EmergencyServicesOrganization organization;

    private UserAccount userAccount;
    private EcoSystem business;

    public CheckDonor(JPanel userProcessContainer, UserAccount account, Organization organization, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.business = business;
        this.organization = (EmergencyServicesOrganization) organization;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        ssnTxt = new javax.swing.JTextField();
        checkBtn = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setText("SSN");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 168, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setText("Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, -1, -1));
        add(nameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 150, -1));
        add(ssnTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 150, -1));

        checkBtn.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        checkBtn.setText("Check");
        checkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBtnActionPerformed(evt);
            }
        });
        add(checkBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, -1, -1));

        backJButton.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void checkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBtnActionPerformed
        // TODO add your handling code here:
        Donor donor=new Donor();
        String dname = nameTxt.getText();
        String dssn = ssnTxt.getText();
        for (Network net : business.getNetworkList()) {
            for (Enterprise ent : net.getEnterpriseDirectory().getEnterpriseList()) {
//                System.out.println(ent.getEnterpriseType().toString());
                if (ent.getEnterpriseType().toString().equals("United Network of Organ Sharing")) {
                    for (UserAccount user : ent.getUserAccountDirectory().getUserAccountList()) {
//                        System.out.println(user.getRole().toString());
                        if (user.getRole().toString().equals("Business.Role.DonorRole")) {
                            String name = ((Donor) user).getInfo().getName();
                            String ssn = ((Donor) user).getInfo().getSsn();
                            if (name.equals(dname) && ssn.equals(dssn)) {
                                donor =  (Donor) user;
                                ((Donor) user).setStatus(false);
                            }
                        }
                    }
                }
            }
        }

        RecieverWorkReq req = new RecieverWorkReq();
        req.setDonor(donor);
        req.setStatus("Sent to OPTC");
        req.setSender(userAccount);
         for (Network network : business.getNetworkList()) {
                for (Enterprise ent : network.getEnterpriseDirectory().getEnterpriseList()) {
                    if(ent.getEnterpriseType().toString().equals("Organ Procurement and Transplant Center")){  
                        for(Organization org:ent.getOrganizationDirectory().getOrganizationList()){
                            org.getWorkQueue().addRequest(req);                           
                        }
                    }
                }
            }

    }//GEN-LAST:event_checkBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton checkBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JTextField ssnTxt;
    // End of variables declaration//GEN-END:variables
}
