/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AmbulanceWorkArea;

import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.EmergencyReq;
import Business.WorkQueue.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chief_kmv
 */
public class AmbulanceMainArea extends javax.swing.JPanel {

    /**
     * Creates new form AmbulanceMainArea
     */
    JPanel userProcessContainer;
    UserAccount account;
    Organization organization;
    public AmbulanceMainArea(JPanel userProcessContainer, UserAccount account, Organization organization) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.account=account;
        this.organization=organization;
        populateAmbulanceTable();
        populateCombo();
    }
     public void populateAmbulanceTable() {
        DefaultTableModel model = (DefaultTableModel) emergencyRequestTable1.getModel();

        model.setRowCount(0);
        for (WorkRequest r : organization.getWorkQueue().getWorkRequestList()) {
            
            Object[] row = new Object[4];
            row[0] = r;
            row[1] = ((EmergencyReq) r).getOrganReciever();
            row[2] = ((EmergencyReq) r).getOrganReciever().getInfo().getAddress();
            row[3] = r.getStatus();
            model.addRow(row);
        }
    }
     public void populateCombo() {
        ambulanceCombo.removeAllItems();

       ambulanceCombo.addItem("On the way");
       ambulanceCombo.addItem("Picked up Organ Reciever");
       ambulanceCombo.addItem("Organ Reciever Dropped at Hospital");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        emergencyRequestTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        ambulanceCombo = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        emergencyRequestTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Request ID", "Organ Reciever", "Address", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(emergencyRequestTable1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 480, 90));

        jButton2.setBackground(new java.awt.Color(255, 159, 28));
        jButton2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jButton2.setText("Update Status");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, -1, -1));

        ambulanceCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(ambulanceCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 170, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setText("Change Status");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, -1, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/Ambulance.gif"))); // NOI18N
        jLabel3.setText("jLabel3");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 740, 320));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int selectedRow = emergencyRequestTable1.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table to view details", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {

            EmergencyReq req = (EmergencyReq) emergencyRequestTable1.getValueAt(selectedRow, 0);
            if(req.getStatus().equals("Organ Reciever Dropped at Hospital")){
                JOptionPane.showMessageDialog(null, "You cannot process old requests");
            }else{
                req.setStatus((String) ambulanceCombo.getSelectedItem());
            }
            
            populateAmbulanceTable();

        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ambulanceCombo;
    private javax.swing.JTable emergencyRequestTable1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
